### ISSUE TITLE
EmailsText not created for Emails

### ISSUE THREAD

**Issue by crazytonyi** [sugarcrm/Tidbit#26]
Just tested with default settings using

`php install_cli.php -l 1000`

which generated 16000 rows on `emails` table (as expected) but no rows created on `emails_text` table. This relationship is essentially atomic (neither "module" record makes sense without the other), and may not be easily definable under "tidbit_relationships", since the emails_text table doesn't have it's own true unique ID key, but instead uses the `email_id` column as the primary key, which is also the foreign key for the related email record. So the entry *might* look similar to:

```
$tidbit_relationships['EmailText'] = array(
    'Emails' => array(
        'self' => 'email_id',
        'you' => 'email_id',
        'table' => 'emails_text'
    ),
);
```

But it's not at all clear (to me) if the above would be the way to go. This may be a documentation issue (in terms of making it clear how to handle various relationships), or may be a needed addition to the application (basically defining how this sort of relationship would get handled), or may reflect a need in the application for handling "tight" or "non-optional" one-to-one relationships, or even a need to hard-code this specific use-case into the application (as it seems like it is very atypical and likely not the "right" way we would implement such a pattern if we started from scratch).

Conceptually, I think this relationship would be considered "bijective" (if that is at all helpful to the power-math-nerds out there): 

https://en.wikipedia.org/wiki/Bijection

**Comment by izhutaev-sugarcrm** [comment]
Hi @crazytonyi, thanks for bring this up. We are working on updates to populate both emails and emails_text tables with Tidbit. I will update this issue when it will be ready and merged.

**Comment by izhutaev-sugarcrm** [comment]
Hi @crazytonyi, we have solved emails_text generation issue in "develop" branch https://github.com/sugarcrm/Tidbit/tree/develop please check if it work's for you. We are going to update master soon.

**Comment by izhutaev-sugarcrm** [comment]
changes are in `master` branch, **EmailText** table will be populated by default with same number of records as **Emails** and `email_id` will be associated `id` in "emails" table
