### ISSUE TITLE
On DB2 vagrant stack not able to create account records.

### ISSUE THREAD

**Issue by sverma-sugarcrm** [sugarcrm/Tidbit#51]
[vagrant@php54-db2-stack Tidbit]$ php install_cli.php -l 10
Constructing
0 Teams
0 EmailAddresses
0 ACLRoles
0 Users
10 Accounts
0 Quotes
0 ProductBundles
0 Products
0 Calls
0 Emails
0 Contacts
0 Leads
0 Opportunities
0 Cases
0 Bugs
0 Meetings
0 Tasks
0 Notes
0 Documents
0 Categories
0 KBContents

With Clean Mode OFF
With Turbo Mode OFF
With Transaction Batch Mode 0
With Obliterate Mode OFF
With Existing Users Mode OFF
With ActivityStream Populating Mode OFF
With 10 teams in Team Sets
With Team-based ACL Mode OFF
With Team-based Restriction Level OFF

Processing Module Teams
Inserting 0 records.

```
    *Hitting DB... Database failure.* Please refer to sugarcrm.log for details.Database failure. Please refer to sugarcrm.log for details.[vagrant@php54-db2-stack Tidbit]$
```

> Sugarcrm.log says following error:

Mon Jun 20 23:44:45 2016 [7150][-none-][FATAL] INSERT QUERY FAILED Query Failed: INSERT INTO team_sets ( id, name, team_md5, team_count, date_modified) VALUES ('a3c5407a-377b-11e6-99dc-56847afe9799', '55ff757c5f6e588a541befae3e662c68', '55ff757c5f6e588a541befae3e662c68', 10, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3c68246-377b-11e6-9d0a-56847afe9799', 'b862cc37cba09f330899c1cafe4b344c', 'b862cc37cba09f330899c1cafe4b344c', 9, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3c71c2e-377b-11e6-ba05-56847afe9799', '93960e5e94d61b97790dac88c75bca20', '93960e5e94d61b97790dac88c75bca20', 8, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3c9a34a-377b-11e6-8e7d-56847afe9799', 'f033b79788d955355b172a3dce6f0140', 'f033b79788d955355b172a3dce6f0140', 7, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3ca10e6-377b-11e6-aaf4-56847afe9799', '2981efc8e379096e8a27858ab337fc36', '2981efc8e379096e8a27858ab337fc36', 6, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3cc90e6-377b-11e6-bf72-56847afe9799', '156b61adf6525511793e4b30dbd1993e', '156b61adf6525511793e4b30dbd1993e', 5, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3ccf662-377b-11e6-902f-56847afe9799', '98ff04595d28116dd8787b468b612de0', '98ff04595d28116dd8787b468b612de0', 4, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3cd50d0-377b-11e6-8bb2-56847afe9799', '9d8cae4502ff595ab9020ccc6ab41d32', '9d8cae4502ff595ab9020ccc6ab41d32', 3, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3cd9dba-377b-11e6-8ab2-56847afe9799', '9bb1e38db063660e9f22ba67d8688f2b', '9bb1e38db063660e9f22ba67d8688f2b', 2, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('1                                   ', '69bc0547e5860dca6da3f25368522dc9', '69bc0547e5860dca6da3f25368522dc9', 1, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3cdf116-377b-11e6-a4ff-56847afe9799', '3b471e58a0c491294f43643eb307ff53', '3b471e58a0c491294f43643eb307ff53', 10, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d0b7ca-377b-11e6-a7ac-56847afe9799', 'ec230164930cf8cc5e3a95387c488a6a', 'ec230164930cf8cc5e3a95387c488a6a', 9, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d145be-377b-11e6-9e78-56847afe9799', '910347f19b73d6c9db8548ca147907ef', '910347f19b73d6c9db8548ca147907ef', 8, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d3a048-377b-11e6-84fa-56847afe9799', '360cf04ba11cfc68f5a67b23d0976e48', '360cf04ba11cfc68f5a67b23d0976e48', 7, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d41ff0-377b-11e6-b565-56847afe9799', '4c869f72f3709197684d4dda2d3106d6', '4c869f72f3709197684d4dda2d3106d6', 6, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d4b4ec-377b-11e6-b8cd-56847afe9799', '8b1c29b3bc73b5a7ff1b26d5eff24bfc', '8b1c29b3bc73b5a7ff1b26d5eff24bfc', 5, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d6db14-377b-11e6-9d2b-56847afe9799', 'a46b2a94f6e30a5a21aae3b14fc77427', 'a46b2a94f6e30a5a21aae3b14fc77427', 4, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d7413a-377b-11e6-ab26-56847afe9799', '3b1e226bda2750fc906a708090a89c9e', '3b1e226bda2750fc906a708090a89c9e', 3, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('a3d794dc-377b-11e6-a6bc-56847afe9799', '41d3cc50703336e99def1350b04c7a2c', '41d3cc50703336e99def1350b04c7a2c', 2, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS')),('fb87d846-33b5-11e6-bab7-56847afe9799', '088920ca99d7039dcbbb989aa7fc33ac', '088920ca99d7039dcbbb989aa7fc33ac', 1, to_date('2016-06-21 06:44:43', 'YYYY-MM-DD HH24:MI:SS'));: _IBM_DB2 statement error 23505: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "1" constrains table "DB2INST1.TEAM_SETS" from having duplicate values for the index key.  SQLSTATE=23505 SQLCODE=-803_

**Comment by izhutaev-sugarcrm** [comment]
Thanks for the bug report, we will look on this issue and come back with more details

**Comment by izhutaev-sugarcrm** [comment]
@sverma-sugarcrm I've just merged PR with fixes into "develop" branch. Could you please try to checkout Tidbit "develop" branch and try it on db2 stack? You need to specify one additional CLI argument to run it on DB2 ```--storage db2```

Examples :
Obliterate mode (will remove all data in db tables and generate new)
```php install_cli.php -u 20 -l 1000 -o --storage db2 --sugar_path /path/to/sugar```
Use Existing Users/Teams
```php install_cli.php -u 20 -l 1000 -e --storage db2 --sugar_path /path/to/sugar```

Note: Your bugs was related to Teams generation, cause you do not specified "-o" or "-e" flags, but we also fixed bugs with auto increment fields in quotes, cases, bugs tables and fix user_preferences generation.

Please let me know, if you have feature issues. Thanks

**Comment by sverma-sugarcrm** [comment]
Tried with the merged PR on develop branch for other modules it's populating data but for: Quotes, Cases and Bugs.
It is giving following error:
`[17900][-none-][FATAL]  Query Failed: SELECT last_number as current_val FROM user_sequences WHERE sequence_name='CASES_CASE_NUMBER_SEQ': IBM_DB2 statement error 42S02: [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N  "DB2INST1.USER_SEQUENCES" is an undefined name.  SQLSTATE=42704 SQLCODE=-204`

Now if it fails in this step the next query also keeps failing:

`[-none-][FATAL] INSERT QUERY FAILED Query Failed: INSERT INTO cases
.
.
.
: IBM_DB2 statement error 23505: [IBM][CLI Driver][DB2/LINUXX8664] SQL0803N  One or more values in the INSERT statement, UPDATE statement, or foreign key update caused by a DELETE statement are not valid because the primary key, unique constraint or unique index identified by "6" constrains table "DB2INST1.CASES" from having duplicate values for the index key.  SQLSTATE=23505 SQLCODE=-803`

**Comment by izhutaev-sugarcrm** [comment]
@sverma-sugarcrm could you please tell me which version of Sugar do you using? 
And exact CLI arguments you run Tidbit with.
I will try to set it up on DB2 vagrant stack and try to test. 
This error is related to auto increment fields in Cases, Quotes and Bugs modules
Thanks!

**Comment by sverma-sugarcrm** [comment]
The DB2 stack is used on Vagrant(stack-131), 7.8.0.0RC4 build-171.
The command used is: `php install_cli.php -l 10 -o --storage db2 --sugar_path /var/www/html/SugarEnt-7.8.0.0RC4/`

PFA [sugarcrm.log](https://github.com/sugarcrm/Tidbit/files/354037/sugarcrm.txt).
PFA [cmd execution logs](https://github.com/sugarcrm/Tidbit/files/354051/Cmd_Output.txt)

**Comment by izhutaev-sugarcrm** [comment]
@sverma-sugarcrm I've merged fix into develop branch, now Tidbit will use "SYSIBM.SYSSEQUENCES" table to fetch current sequence value. 
Could you please try "develop" branch again? Thanks!

**Comment by sverma-sugarcrm** [comment]
@izhutaev-sugarcrm Now it is not allowing to remove users:
The DB2 stack is used on Vagrant(stack-131), 7.8.0.0 build-1383.

`[vagrant@php54-db2-stack Tidbit]$ php install_cli.php -l 10 -o --storage db2 --sugar_path /var/www/html/SugarEnt-7.8.0.0/
Constructing
0.2 Teams
1 Users
120 EmailAddresses
. . .
Obliterating activities ...
Processing Module Teams
Inserting 0.2 records.
        Obliterating all existing data ... DONE
        Hitting DB... * DONE
        Time spend... 0.132852s
Processing Module Users
Inserting 1 records.
        Obliterating all existing data ...`

No execution shows after this, it just stopped here.  Here are the [sugarcrm](https://github.com/sugarcrm/Tidbit/files/361220/sugarcrm.txt) logs.

**Comment by izhutaev-sugarcrm** [comment]
@sverma-sugarcrm I've tried it with 7.8.0.0 version and your command ```php install_cli.php -l 10 -o --storage db2 --sugar_path /var/www/html/SugarEnt-7.8.0.0/``` works fine for me...
There is a php_errors.log file in /var/www/html/ folder - maybe there are some errors?

I destroyed and spin DB2 vagrant box from the beginning, have no issues.

Also, 
- make sure DB2 is running and your are able to connect to it
- make sure you can open sugar instance and login to it with admin
