### ISSUE TITLE
Where is no Sugar on path /var/www/html/sugar/Tidbit/config/.. ... exiting

### ISSUE THREAD

**Issue by maestrofx** [sugarcrm/Tidbit#69]
Hi everyone,

I got an error something like:

> Where is no Sugar on path /var/www/html/sugar/Tidbit/config/.. ... exiting

when executing install_cli.php

Any comments are welcome.
Thank you.

**Comment by maestrofx** [comment]
Hi @izhutaev-sugarcrm ,
It doesn't fix this problem yet.

I've tried to fix default value to **DIR** "../.." instead of **DIR** . "/..", but it's still the same.


`# php -f install_cli.php -- --sugar_path /var/www/html/sugar`

```
PHP Warning:  require_once(/var/www/html/sugar/modules/Teams/TeamSet.php): failed to open stream: No such file or directory in /var/www/html/sugar/install/Tidbit/bootstrap.php on line 227
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/sugar/modules/Teams/TeamSet.php' (include_path='/var/www/html/sugar/include/..:.:/usr/share/php:/usr/share/pear') in /var/www/html/sugar/install/Tidbit/bootstrap.php on line 227
```

**Comment by izhutaev-sugarcrm** [comment]
@maestrofx it seems like a different issue right now, cause before Tidbit can't find Sugar installation folder and now it can't load TeamSet.php file with TeamSets bean.

Could you please make sure your folder "/var/www/html/sugar/" contains Sugar installation? "modules/Teams/TeamSet.php" file should there too.

Also, could you please tell me, what version of Sugar your are using? Thanks!

**Comment by izhutaev-sugarcrm** [comment]
@maestrofx have you able to fix an issue? Please let me know, if you need further help? Thanks

**Comment by izhutaev-sugarcrm** [comment]
Master branch was updated with a fix. Closing this issue, please open another one if you still have issues.
